[2024-10-20T17:32:03.702+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_to_minio.run_transfer_to_minio manual__2024-10-20T17:30:47.538266+00:00 [queued]>
[2024-10-20T17:32:03.707+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_to_minio.run_transfer_to_minio manual__2024-10-20T17:30:47.538266+00:00 [queued]>
[2024-10-20T17:32:03.707+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-20T17:32:03.713+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_transfer_to_minio> on 2024-10-20 17:30:47.538266+00:00
[2024-10-20T17:32:03.716+0000] {standard_task_runner.py:60} INFO - Started process 598 to run task
[2024-10-20T17:32:03.718+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdc_to_minio', 'run_transfer_to_minio', 'manual__2024-10-20T17:30:47.538266+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_cdc_to_minio.py', '--cfg-path', '/tmp/tmplsl456hq']
[2024-10-20T17:32:03.720+0000] {standard_task_runner.py:88} INFO - Job 242: Subtask run_transfer_to_minio
[2024-10-20T17:32:03.744+0000] {task_command.py:423} INFO - Running <TaskInstance: cdc_to_minio.run_transfer_to_minio manual__2024-10-20T17:30:47.538266+00:00 [running]> on host ac960a3ccd9e
[2024-10-20T17:32:03.782+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_to_minio' AIRFLOW_CTX_TASK_ID='run_transfer_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T17:30:47.538266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T17:30:47.538266+00:00'
[2024-10-20T17:32:03.783+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-20T17:32:03.783+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/src/other_services/transfer_to_minio.py']
[2024-10-20T17:32:03.788+0000] {subprocess.py:86} INFO - Output:
[2024-10-20T17:33:20.033+0000] {subprocess.py:93} INFO - Error connect to Redis: Error 111 connecting to redis:6379. Connection refused.
[2024-10-20T17:33:20.042+0000] {subprocess.py:93} INFO - Connected to Minio
[2024-10-20T17:33:20.079+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-20T17:33:20.116+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cdc_to_minio, task_id=run_transfer_to_minio, execution_date=20241020T173047, start_date=20241020T173203, end_date=20241020T173320
[2024-10-20T17:33:20.134+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-20T17:33:20.148+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
