[2024-10-20T18:51:57.055+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_to_minio.run_transfer_to_minio manual__2024-10-20T18:50:39.519563+00:00 [queued]>
[2024-10-20T18:51:57.060+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_to_minio.run_transfer_to_minio manual__2024-10-20T18:50:39.519563+00:00 [queued]>
[2024-10-20T18:51:57.060+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-20T18:51:57.066+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_transfer_to_minio> on 2024-10-20 18:50:39.519563+00:00
[2024-10-20T18:51:57.069+0000] {standard_task_runner.py:60} INFO - Started process 322 to run task
[2024-10-20T18:51:57.071+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdc_to_minio', 'run_transfer_to_minio', 'manual__2024-10-20T18:50:39.519563+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_cdc_to_minio.py', '--cfg-path', '/tmp/tmpx7vjgzch']
[2024-10-20T18:51:57.073+0000] {standard_task_runner.py:88} INFO - Job 246: Subtask run_transfer_to_minio
[2024-10-20T18:51:57.098+0000] {task_command.py:423} INFO - Running <TaskInstance: cdc_to_minio.run_transfer_to_minio manual__2024-10-20T18:50:39.519563+00:00 [running]> on host ac960a3ccd9e
[2024-10-20T18:51:57.135+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_to_minio' AIRFLOW_CTX_TASK_ID='run_transfer_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T18:50:39.519563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T18:50:39.519563+00:00'
[2024-10-20T18:51:57.136+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-20T18:51:57.137+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/src/other_services/transfer_to_minio.py']
[2024-10-20T18:51:57.142+0000] {subprocess.py:86} INFO - Output:
[2024-10-20T18:53:12.356+0000] {subprocess.py:93} INFO - Error connect to Redis: Error 111 connecting to redis:6379. Connection refused.
[2024-10-20T18:53:12.363+0000] {subprocess.py:93} INFO - Connected to Minio
[2024-10-20T18:53:12.406+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-20T18:53:12.435+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cdc_to_minio, task_id=run_transfer_to_minio, execution_date=20241020T185039, start_date=20241020T185157, end_date=20241020T185312
[2024-10-20T18:53:12.451+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-20T18:53:12.467+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
